# All files translated by the community by at least some locales should
# be covered by the [[paths]] in this file.

basepath = "."

locales = [
    "de",
    "fr",
    "it"
]

[[paths]]
    reference = "en-US/*.ftl"
    l10n = "{locale}/*.ftl"
